// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Aug 30 17:17:03 2022

Adder_module Adder_module_inst
(
	.a(a_sig) ,	// input [2:0] a_sig
	.b(b_sig) ,	// input [2:0] b_sig
	.c_in(c_in_sig) ,	// input  c_in_sig
	.s(s_sig) ,	// output [2:0] s_sig
	.c_out(c_out_sig) 	// output [2:0] c_out_sig
);

